// <auto-generated />
namespace App_Controle_Dengue_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Testev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Testev1));
        
        string IMigrationMetadata.Id
        {
            get { return "202006100005055_Testev1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
